# Generated by Django 6.0.3 on 2026-04-03 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial_saas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom(s)')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], default='A', max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession')),
                ('est_assure', models.BooleanField(default=False, verbose_name='Est assuré ?')),
                ('assurance', models.CharField(blank=True, max_length=100, null=True, verbose_name="Compagnie d'assurance")),
                ('code_assurance', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Police')),
                ('pourcentage', models.DecimalField(blank=True, decimal_places=2, help_text='Ex : 80.00 pour 80%', max_digits=5, null=True, verbose_name='Prise en charge (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='users.clinic', verbose_name='Clinique')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
