# Generated by Django 6.0.3 on 2026-04-03 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial_saas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='N° Facture')),
                ('date', models.DateField(verbose_name='Date')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('payee', 'Payée'), ('partielle', 'Partiellement payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('virement', 'Virement'), ('assurance', 'Assurance'), ('autre', 'Autre')], max_length=20, verbose_name='Mode de paiement')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant payé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caissier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='users.clinic', verbose_name='Clinique')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ('-date',),
            },
        ),
    ]
