# Generated by Django 6.0.4 on 2026-04-09 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='montant_paye',
        ),
        migrations.AddField(
            model_name='facture',
            name='assurance_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° Police'),
        ),
        migrations.AddField(
            model_name='facture',
            name='assurance_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Compagnie'),
        ),
        migrations.AddField(
            model_name='facture',
            name='est_assure',
            field=models.BooleanField(default=False, verbose_name='Patient assuré'),
        ),
        migrations.AddField(
            model_name='facture',
            name='part_assurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Part assurance'),
        ),
        migrations.AddField(
            model_name='facture',
            name='part_patient',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Part patient'),
        ),
        migrations.AddField(
            model_name='facture',
            name='taux_assurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux prise en charge (%)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('virement', 'Virement'), ('assurance', 'Assurance'), ('mobile', 'Mobile Money'), ('autre', 'Autre')], max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payeur', models.CharField(choices=[('patient', 'Patient'), ('assurance', 'Assurance')], default='patient', max_length=20, verbose_name='Payeur')),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('virement', 'Virement'), ('mobile', 'Mobile Money'), ('autre', 'Autre')], default='especes', max_length=20, verbose_name='Mode de paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('caissier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='factures.facture', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ('-date',),
            },
        ),
    ]
