# Generated by Django 6.0.4 on 2026-04-09 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_remove_facture_montant_paye_facture_assurance_code_and_more'),
        ('soins', '0003_soinacte'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='soin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture', to='soins.soin', verbose_name='Soin lié'),
        ),
    ]
