# Generated by Django 6.0.4 on 2026-04-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_cours', max_length=20, verbose_name='Statut'),
        ),
    ]
