# Generated by Django 6.0.3 on 2026-04-03 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('users', '0001_initial_saas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(verbose_name='Date et heure')),
                ('duree_minutes', models.PositiveIntegerField(default=30, verbose_name='Durée (min)')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('en_salle', "En salle d'attente"), ('effectue', 'Effectué'), ('annule', 'Annulé'), ('absent', 'Patient absent')], default='planifie', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='users.clinic', verbose_name='Clinique')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to=settings.AUTH_USER_MODEL, verbose_name='Médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ('date_heure',),
            },
        ),
    ]
