# Generated by Django 6.0.3 on 2026-04-03 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial_saas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('medical', 'Médical'), ('chirurgical', 'Chirurgical'), ('familial', 'Familial'), ('autre', 'Autre')], default='medical', max_length=20, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Antécédent',
                'verbose_name_plural': 'Antécédents',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('', 'Inconnu')], max_length=3, verbose_name='Groupe sanguin')),
                ('antecedents', models.TextField(blank=True, verbose_name='Antécédents médicaux')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('traitements_en_cours', models.TextField(blank=True, verbose_name='Traitements en cours')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='users.clinic', verbose_name='Clinique')),
            ],
            options={
                'verbose_name': 'Dossier médical',
                'verbose_name_plural': 'Dossiers médicaux',
            },
        ),
    ]
