# Generated by Django 6.0.3 on 2026-04-03 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('users', '0001_initial_saas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_soin', models.CharField(max_length=150, verbose_name='Type de soin')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('effectue', 'Effectué'), ('annule', 'Annulé')], default='planifie', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='users.clinic', verbose_name='Clinique')),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to=settings.AUTH_USER_MODEL, verbose_name='Infirmier(ère)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Soin',
                'verbose_name_plural': 'Soins',
                'ordering': ('-date',),
            },
        ),
    ]
