# Generated by Django 6.0.3 on 2026-04-04 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_initial'),
        ('soins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soin',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='consultations.consultation', verbose_name='Consultation liée'),
        ),
    ]
