# Generated by Django 6.0.3 on 2026-04-04 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0002_soin_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoinActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acte', models.CharField(max_length=200, verbose_name='Acte réalisé')),
                ('qte', models.PositiveSmallIntegerField(default=1, verbose_name='Quantité')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (GNF)')),
                ('soin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actes', to='soins.soin', verbose_name='Soin')),
            ],
            options={
                'verbose_name': 'Acte de soin',
                'verbose_name_plural': 'Actes de soin',
            },
        ),
    ]
