# Generated by Django 6.0.3 on 2026-04-03 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('users', '0001_initial_saas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=200, verbose_name='Médicament')),
                ('posologie', models.CharField(max_length=200, verbose_name='Posologie')),
                ('duree', models.CharField(blank=True, max_length=100, verbose_name='Durée')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
            ],
            options={
                'verbose_name': "Ligne d'ordonnance",
                'verbose_name_plural': "Lignes d'ordonnance",
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('notes', models.TextField(blank=True, verbose_name='Instructions / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='users.clinic', verbose_name='Clinique')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances', to='consultations.consultation', verbose_name='Consultation')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances', to=settings.AUTH_USER_MODEL, verbose_name='Médecin')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
                'ordering': ('-date',),
            },
        ),
    ]
