# Generated by Django 6.0.3 on 2026-04-03 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('users', '0001_initial_saas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(max_length=200, verbose_name="Type d'examen")),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('compte_rendu', models.TextField(blank=True, verbose_name='Compte rendu')),
                ('image', models.FileField(blank=True, null=True, upload_to='radiologie/', verbose_name='Image / Fichier')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('realise', 'Réalisé'), ('interprete', 'Interprété'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_radio', to='users.clinic', verbose_name='Clinique')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_radio_demandes', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_radio', to='patients.patient', verbose_name='Patient')),
                ('radiologue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_radio_interpretes', to=settings.AUTH_USER_MODEL, verbose_name='Radiologue')),
            ],
            options={
                'verbose_name': 'Examen radiologique',
                'verbose_name_plural': 'Examens radiologiques',
                'ordering': ('-date',),
            },
        ),
    ]
