# Generated by Django 6.0.3 on 2026-04-03 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial_saas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('forme', models.CharField(choices=[('comprimes', 'Comprimés'), ('gelules', 'Gélules'), ('sirop', 'Sirop'), ('injectable', 'Injectable'), ('pommade', 'Pommade'), ('gouttes', 'Gouttes'), ('autre', 'Autre')], default='comprimes', max_length=20, verbose_name='Forme')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='Dosage')),
                ('unite', models.CharField(blank=True, max_length=50, verbose_name='Unité (boîte, flacon…)')),
                ('stock_actuel', models.PositiveIntegerField(default=0, verbose_name='Stock actuel')),
                ('stock_min', models.PositiveIntegerField(default=5, verbose_name='Stock minimum')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='users.clinic', verbose_name='Clinique')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement')], max_length=20, verbose_name='Type')),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='pharmacie.medicament', verbose_name='Médicament')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ('-date',),
            },
        ),
    ]
