# Generated by Django 6.0.3 on 2026-04-03 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial_saas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenLabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(max_length=200, verbose_name="Type d'examen")),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_resultat', models.DateTimeField(blank=True, null=True, verbose_name='Date du résultat')),
                ('resultat', models.TextField(blank=True, verbose_name='Résultat')),
                ('valeurs_normales', models.TextField(blank=True, verbose_name='Valeurs normales')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_labo', to='users.clinic', verbose_name='Clinique')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_labo_demandes', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('laborantin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_labo_traites', to=settings.AUTH_USER_MODEL, verbose_name='Laborantin')),
            ],
            options={
                'verbose_name': 'Examen de laboratoire',
                'verbose_name_plural': 'Examens de laboratoire',
                'ordering': ('-date_demande',),
            },
        ),
    ]
