# Generated by Django 6.0.3 on 2026-04-03 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la clinique')),
                ('type', models.CharField(choices=[('generale', 'Clinique générale / Polyclinique'), ('dentaire', 'Clinique dentaire'), ('pediatrique', 'Clinique pédiatrique'), ('ophtalmologie', 'Clinique ophtalmologique'), ('maternite', 'Maternité'), ('psychiatrie', 'Clinique psychiatrique')], max_length=50, verbose_name='Type de clinique')),
                ('slug', models.SlugField(help_text='Généré automatiquement depuis le nom.', max_length=220, unique=True, verbose_name='Identifiant unique')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinics/logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
            ],
            options={
                'verbose_name': 'Clinique',
                'verbose_name_plural': 'Cliniques',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('telephone', models.CharField(help_text='Utilisé comme identifiant de connexion.', max_length=30, unique=True, verbose_name='Téléphone')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse email')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Avatar')),
                ('group', models.CharField(help_text='Dépend du type de clinique.', max_length=50, verbose_name='Groupe')),
                ('permission', models.CharField(choices=[('CRUD', 'Créer, Lire, Mettre à jour, Supprimer'), ('CRU', 'Créer, Lire, Mettre à jour'), ('CR', 'Créer, Lire'), ('C', 'Créer uniquement')], default='C', max_length=4, verbose_name='Permission')),
                ('modules', models.JSONField(blank=True, default=list, verbose_name='Modules accessibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superutilisateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.clinic', verbose_name='Clinique')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
