# Generated by Django 6.0.4 on 2026-04-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_saas'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Abonnement actif'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='subscribed_plan',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Plan souscrit'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='trial_ends_at',
            field=models.DateField(blank=True, null=True, verbose_name="Fin d'essai"),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('CRUD', 'Créer, Lire, Mettre à jour, Supprimer'), ('CRU', 'Créer, Lire, Mettre à jour'), ('CR', 'Créer, Lire'), ('C', 'Créer uniquement'), ('R', 'Lire uniquement')], default='C', max_length=4, verbose_name='Permission'),
        ),
    ]
