# Generated by Django 6.0.3 on 2026-04-03 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial_saas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chambre', models.CharField(blank=True, max_length=50, verbose_name='Chambre / Lit')),
                ('motif', models.TextField(verbose_name="Motif d'hospitalisation")),
                ('date_entree', models.DateTimeField(verbose_name="Date d'entrée")),
                ('date_sortie_prevue', models.DateField(blank=True, null=True, verbose_name='Date de sortie prévue')),
                ('date_sortie_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Date de sortie réelle')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('sortie', 'Sorti(e)'), ('transfere', 'Transféré(e)'), ('annule', 'Annulé')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Évolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='users.clinic', verbose_name='Clinique')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations', to=settings.AUTH_USER_MODEL, verbose_name='Médecin responsable')),
            ],
            options={
                'verbose_name': 'Hospitalisation',
                'verbose_name_plural': 'Hospitalisations',
                'ordering': ('-date_entree',),
            },
        ),
    ]
